name: CI/CD Pipeline

on:
  push:
    branches: [main]  # Or "master" if that's your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 src --max-line-length=120 || echo "Linting failed but continuing."

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlops-housing-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-housing-app:latest
